export const COPY = {
  appName: 'TempoLoop',
  common: {
    cancel: 'Cancel',
    clear: 'Clear',
    delete: 'Delete',
    rename: 'Rename',
    retry: 'Try Again',
    save: 'Save',
    set: 'Set',
    settings: 'Open Settings',
  },
  projectList: {
    headingAccessibilityLabel: 'TempoLoop project library',
    extractVideo: 'Extract from Video',
    importAudio: 'Import Audio',
    extractVideoAccessibilityHint: 'Choose a local video from the Android gallery.',
    importAudioAccessibilityHint:
      'Choose an audio file from Android storage, including a renamed M4S audio file.',
    emptyTitle: 'Start your first practice project',
    emptyMessage: 'Extract a video soundtrack or import an audio file for offline dance practice.',
    loading: 'Loading projects...',
    loadErrorTitle: 'Projects could not be loaded',
    loadErrorMessage:
      'TempoLoop could not read your project library. Your local files have not been deleted.',
    projectOpenAccessibilityHint: 'Opens this practice project.',
    projectActionsAccessibilityHint:
      'Double tap to open. Use the available actions to rename or delete.',
    projectMenuAccessibilityLabel: (projectName: string) => `Project menu for ${projectName}`,
    renameTitle: 'Rename Project',
    renameMessage: 'Enter a name for this practice project.',
    deleteTitle: (projectName: string) => `Delete "${projectName}"?`,
    deleteMessage:
      'This permanently removes the project audio, waveform, and segment settings from this Android device.',
    actionErrorTitle: 'Project could not be updated',
    actionErrorMessage:
      'TempoLoop could not save that change. Your existing project data is unchanged.',
    projectSummary: (duration: string, configuredCount: number) =>
      `${duration} \u00b7 ${configuredCount} of 9 segments`,
    projectAccessibilitySummary: (duration: string, configuredCount: number) =>
      `${duration}, ${configuredCount} of 9 segments configured`,
    updated: (date: string) => `Updated ${date}`,
    updatedUnknown: 'Unknown date',
    waveformStatus: {
      pending: 'Building waveform',
      ready: 'Waveform ready',
      failed: 'Waveform unavailable',
    },
    waveformBlocksImport: 'Finish building the current waveform before importing again.',
    repairStatus: 'Needs repair',
    repairAudioMissing: 'Audio is missing or empty.',
    repairWaveformMissing: 'Waveform is missing.',
    repairWaveformInvalid: 'Waveform data cannot be read.',
    repairWaveformDurationMismatch: 'Waveform duration does not match the project.',
    repairUnknownReason: 'Project media could not be read.',
    repairDeleteAccessibilityLabel: (projectName: string) => `Delete project ${projectName}`,
    repairDeleteAccessibilityHint:
      'Deletes this unavailable project from the device after confirmation.',
  },
  import: {
    untitledProjectName: 'Untitled Practice',
    permissionTitle: 'Media picker is unavailable',
    permissionMessage:
      'TempoLoop could not open an Android media picker. Restart the app and try again.',
    pickerErrorTitle: 'Media could not be selected',
    pickerErrorMessage: 'TempoLoop could not use the selected media. Choose a different file.',
    sizeUnavailableMessage:
      'The media size is unavailable. TempoLoop will verify it during import.',
    videoTooLargeMessage: (size: string, maximum: string) =>
      `This video is ${size}. TempoLoop supports videos up to ${maximum}.`,
    audioTooLargeMessage: (size: string, maximum: string) =>
      `This audio file is ${size}. TempoLoop supports audio files up to ${maximum}.`,
    insufficientStorageMessage: 'There is not enough free storage to import this media safely.',
    namingTitle: 'Name This Project',
    namingMessage: 'The original media stays unchanged. TempoLoop keeps only a private audio copy.',
    nameInputLabel: 'Project name',
    confirmLabel: 'Import',
    invalidName: 'Enter a project name between 1 and 80 characters.',
    title: 'Importing Project',
    preparing: 'Preparing media...',
    inspecting: 'Checking media...',
    extracting: 'Extracting audio...',
    exporting: 'Extracting audio...',
    waveform: 'Building waveform...',
    saving: 'Saving project...',
    finalizing: 'Saving project...',
    keepOpen: 'Keep TempoLoop open until the import finishes.',
    cancelling: 'Cancelling...',
    cancelLabel: 'Cancel Import',
    failureTitle: 'Project was not imported',
    failureMessage: 'TempoLoop could not finish this import. No project was saved.',
    postCommitTitle: 'Project imported',
    postCommitMessage:
      'The project was saved, but TempoLoop could not refresh or open it automatically. Your project data was not deleted.',
  },
  mediaErrors: {
    E_VIDEO_TOO_LARGE: 'Select a video smaller than 600 MB.',
    E_AUDIO_TOO_LARGE: 'Select an audio file smaller than 200 MB.',
    E_PICKER_UNAVAILABLE: 'No compatible video picker is available on this device.',
    E_SOURCE_UNREADABLE:
      'TempoLoop could not open this media. Select it again or copy it to local storage.',
    E_NO_AUDIO_TRACK: 'This video does not contain an audio track. Select another video.',
    E_DRM_UNSUPPORTED: 'This protected video cannot be imported. Select an unprotected video.',
    E_INVALID_DURATION: 'This media has an invalid duration. Select another file.',
    E_STORAGE_LOW: 'There is not enough device storage. Free some space and try again.',
    E_IMPORT_BUSY: 'Another import is active. Finish or cancel it before starting another.',
    E_IMPORT_CANCELLED: null,
    E_UNSUPPORTED_MEDIA: 'Use a common video or audio format supported by this Android device.',
    E_OUTPUT_WRITE_FAILED: 'TempoLoop could not save the audio. Free device storage and retry.',
    E_EXPORT_EMPTY: 'The exported audio was empty. Select another media file.',
    E_WAVEFORM_FAILED: 'TempoLoop could not build the waveform. Retry waveform generation.',
    E_INVALID_RANGE: 'Correct the segment start and end times.',
    E_AUDIO_NOT_FOUND: 'The project audio is missing. Delete or restore this project.',
    E_AUDIO_LOAD_FAILED: 'TempoLoop could not load this audio. Re-import the project.',
    E_PLAYBACK_COMMAND_STALE: null,
    E_PATH_OUTSIDE_APP: 'TempoLoop could not use its private output location.',
    E_PROJECT_CORRUPT: 'This project is damaged. Delete or repair it.',
    E_UNKNOWN_NATIVE: 'TempoLoop could not complete that media operation. Try again.',
  },
  practice: {
    backAccessibilityLabel: 'Back to projects',
    settingsAccessibilityLabel: 'Edit segment times',
    speedHeading: 'Playback speed',
    speedAccessibilityLabel: (rateLabel: string) => `${rateLabel} playback speed`,
    leadInHeading: 'Start before segment',
    leadInValue: (seconds: number) => `${seconds} ${seconds === 1 ? 'second' : 'seconds'}`,
    leadInAccessibilityLabel: 'Seconds before segment start',
    segmentsHeading: 'Practice segments',
    segmentLabel: (number: number) => `Segment ${number}`,
    segmentUnavailableHint: 'Set both times in the segment editor to use this segment.',
    play: 'Play',
    pause: 'Pause',
    playAccessibilityLabel: 'Play selected segment',
    pauseAccessibilityLabel: 'Pause playback',
    loadingAudio: 'Preparing audio...',
    audioUnavailable: 'The project audio is not ready. Try loading it again.',
    retryAudio: 'Try Again',
    noConfiguredSegments: 'Set at least one segment to begin practicing.',
    rangeSummary: (start: string, end: string, current: string) =>
      `${start} \u2013 ${end} \u00b7 Current ${current}`,
    projectNotFoundTitle: 'Project not found',
    projectNotFoundMessage: 'TempoLoop could not find this project in the local library.',
    playbackErrorTitle: 'Audio could not be played',
    playbackErrorMessage: 'TempoLoop could not complete that playback action.',
    preferenceErrorTitle: 'Preference could not be saved',
    preferenceErrorMessage:
      'The current choice works for this session, but TempoLoop could not save it.',
  },
  segmentEditor: {
    title: 'Edit Segments',
    waveformLoading: 'Building waveform...',
    waveformProgress: (percent: number) => `Building waveform ${percent}%`,
    waveformError: 'Waveform unavailable. You can still edit and play this project.',
    audioUnavailable: 'The project audio is not ready. Try loading it again.',
    play: 'Play',
    pause: 'Pause',
    currentAndTotal: (current: string, total: string) => `${current} / ${total}`,
    waveformAccessibilityLabel: (
      current: string,
      total: string,
      viewportStart: string,
      viewportEnd: string,
    ) => `Waveform position ${current} of ${total}. Showing ${viewportStart} to ${viewportEnd}.`,
    waveformOverviewAccessibilityLabel: (viewportStart: string, viewportEnd: string) =>
      `Waveform overview showing ${viewportStart} to ${viewportEnd}`,
    segmentLabel: (number: number) => `Segment ${number}`,
    start: 'Start',
    end: 'End',
    setEndpointAccessibilityLabel: (number: number, endpoint: 'start' | 'end') =>
      `Set Segment ${number} ${endpoint}`,
    clearAccessibilityLabel: (number: number) => `Clear Segment ${number}`,
    endpointConfirmation: (endpoint: 'Start' | 'End', time: string) => `${endpoint} set to ${time}`,
    partialError: 'Set both start and end, or clear this segment.',
    nonIntegerError: 'Segment times must use whole milliseconds.',
    outOfBoundsError: 'Segment times must stay within the audio duration.',
    orderError: 'Start must be earlier than end.',
    discardTitle: 'Discard changes?',
    discardMessage: 'Your unsaved segment changes will be lost.',
    discardAction: 'Discard Changes',
    invalidDiscardTitle: 'Incomplete changes cannot be saved',
    invalidDiscardMessage:
      'At least one segment is incomplete or invalid. Discard the entire draft or continue editing.',
    discardAndExit: 'Discard and Exit',
    continueEditing: 'Continue Editing',
    saveErrorTitle: 'Segments could not be saved',
    saveErrorMessage:
      'TempoLoop could not save these segment times. Your existing segments are unchanged.',
    playbackErrorTitle: 'Editor playback failed',
    playbackErrorMessage: 'TempoLoop could not complete that editor playback action.',
    projectNotFoundTitle: 'Project not found',
    projectNotFoundMessage: 'TempoLoop could not find this project in the local library.',
  },
  diagnostics: {
    title: 'Development Diagnostics',
    back: 'Back',
    refresh: 'Refresh',
    clear: 'Clear Diagnostics',
    loading: 'Collecting diagnostics...',
    loadError: 'Diagnostics could not be collected.',
    entryAccessibilityHint: 'Long press to open development diagnostics.',
    mediaSection: 'TempoLoopMedia',
    mediaModuleName: 'Module',
    mediaAvailable: 'Module linked',
    mediaContractVersion: 'Contract version',
    lastMediaError: 'Last media error',
    playbackSection: 'expo-audio Playback',
    playbackMode: 'Mode',
    playbackStatus: 'Status',
    sourceLoaded: 'Source loaded',
    selectedSegment: 'Segment',
    currentTime: 'Current time',
    duration: 'Duration',
    actualRate: 'Rate',
    activeRange: 'Active range',
    commandGeneration: 'Command generation',
    storageSection: 'Storage',
    availableDisk: 'Available disk',
    storageRoot: 'Private root',
    repositorySection: 'Repository',
    projectSchema: 'Project schema',
    waveformSchema: 'Waveform schema',
    repositoryInitialized: 'Initialized',
    projectCount: 'Project count',
    readyProjectCount: 'Ready projects',
    repairProjectCount: 'Projects needing repair',
    corruptProjectCount: 'Corrupt metadata entries',
    repositoryLastError: 'Last repository error code',
    recoveryCodes: 'Recovery diagnostics',
    importSection: 'Import',
    importStoreStatus: 'Store status',
    importCoordinatorActive: 'Coordinator active',
    importStage: 'Stage',
    importStageProgress: 'Stage progress',
    importOverallProgress: 'Overall progress',
    importCancelRequested: 'Cancel requested',
    lastImportError: 'Last import error',
    logSection: 'Bounded Local Log',
    logEmpty: 'No development log entries.',
    yes: 'Yes',
    no: 'No',
    none: 'None',
    unavailable: 'Unavailable',
    segmentValue: (number: number) => `Segment ${number}`,
    progressValue: (progress: number) => `${Math.round(progress * 100)}%`,
    rateValue: (rate: number) => `${rate}x`,
    schemaValue: (version: number) => `v${version}`,
    activeRangeValue: (start: string, end: string) => `${start} to ${end}`,
    timeValue: (formatted: string, milliseconds: number) => `${formatted} (${milliseconds} ms)`,
    logHeading: (timestamp: string, level: string, event: string) =>
      `${timestamp} [${level}] ${event}`,
  },
} as const;
