export const COPY = {
  appName: 'TempoLoop',
  common: {
    cancel: 'Cancel',
    clear: 'Clear',
    delete: 'Delete',
    rename: 'Rename',
    retry: 'Try Again',
    save: 'Save',
    set: 'Set',
    settings: 'Open Settings',
  },
  projectList: {
    headingAccessibilityLabel: 'TempoLoop project library',
    addProjectAccessibilityLabel: 'Import a video',
    emptyTitle: 'Start your first practice project',
    emptyMessage:
      'Import a video and TempoLoop will keep its audio ready for offline dance practice.',
    emptyAction: 'Import Video',
    loading: 'Loading projects...',
    loadErrorTitle: 'Projects could not be loaded',
    loadErrorMessage:
      'TempoLoop could not read your project library. Your local files have not been deleted.',
    projectActionsAccessibilityHint:
      'Double tap to open. Use the available actions to rename or delete.',
    projectActionsTitle: (projectName: string) => `Actions for ${projectName}`,
    renameTitle: 'Rename Project',
    renameMessage: 'Enter a name for this practice project.',
    deleteTitle: (projectName: string) => `Delete "${projectName}"?`,
    deleteMessage:
      'This permanently removes the project audio, waveform, and segment settings from this iPhone.',
    actionErrorTitle: 'Project could not be updated',
    actionErrorMessage:
      'TempoLoop could not save that change. Your existing project data is unchanged.',
    projectSummary: (duration: string, configuredCount: number) =>
      `${duration} \u00b7 ${configuredCount} of 6 segments`,
    projectAccessibilitySummary: (duration: string, configuredCount: number) =>
      `${duration}, ${configuredCount} of 6 segments configured`,
  },
  import: {
    untitledProjectName: 'Untitled Practice',
    permissionTitle: 'Photos access is required',
    permissionMessage:
      'Allow TempoLoop to select a video in iOS Settings. The video is used only for local audio extraction.',
    pickerErrorTitle: 'Video could not be selected',
    pickerErrorMessage: 'TempoLoop could not use the selected video. Choose a different video.',
    notVideoMessage: 'Select a video rather than a photo or Live Photo.',
    sizeUnavailableMessage: 'TempoLoop could not determine the size of this video.',
    videoTooLargeMessage: (size: string, maximum: string) =>
      `This video is ${size}. TempoLoop supports videos up to ${maximum}.`,
    insufficientStorageMessage: 'There is not enough free storage to import this video safely.',
    namingTitle: 'Name This Project',
    namingMessage: 'The original video will not be kept after its audio is imported.',
    nameInputLabel: 'Project name',
    confirmLabel: 'Import',
    invalidName: 'Enter a project name between 1 and 80 characters.',
    title: 'Importing Project',
    preparing: 'Preparing video...',
    extracting: 'Extracting audio...',
    waveform: 'Building waveform...',
    saving: 'Saving project...',
    keepOpen: 'Keep TempoLoop open until the import finishes.',
    cancelling: 'Cancelling...',
    cancelLabel: 'Cancel Import',
    failureTitle: 'Project was not imported',
    failureMessage: 'TempoLoop could not finish this import. No project was saved.',
    postCommitTitle: 'Project imported',
    postCommitMessage:
      'The project was saved, but TempoLoop could not refresh or open it automatically. Your project data was not deleted.',
  },
  practice: {
    backAccessibilityLabel: 'Back to projects',
    settingsAccessibilityLabel: 'Edit segment times',
    speedHeading: 'Playback speed',
    speedAccessibilityLabel: (rateLabel: string) => `${rateLabel} playback speed`,
    segmentsHeading: 'Practice segments',
    segmentLabel: (number: number) => `Segment ${number}`,
    segmentUnavailableHint: 'Set both times in the segment editor to use this segment.',
    play: 'Play',
    pause: 'Pause',
    playAccessibilityLabel: 'Play selected segment',
    pauseAccessibilityLabel: 'Pause playback',
    loadingAudio: 'Preparing audio...',
    audioUnavailable: 'The project audio is not ready. Try loading it again.',
    retryAudio: 'Try Again',
    noConfiguredSegments: 'Set at least one segment to begin practicing.',
    rangeSummary: (start: string, end: string, current: string) =>
      `${start} \u2013 ${end} \u00b7 Current ${current}`,
    projectNotFoundTitle: 'Project not found',
    projectNotFoundMessage: 'TempoLoop could not find this project in the local library.',
    playbackErrorTitle: 'Audio could not be played',
    playbackErrorMessage: 'TempoLoop could not complete that playback action.',
    preferenceErrorTitle: 'Preference could not be saved',
    preferenceErrorMessage:
      'The current choice works for this session, but TempoLoop could not save it.',
  },
  segmentEditor: {
    title: 'Edit Segments',
    waveformLoading: 'Loading waveform...',
    waveformError: 'The waveform could not be loaded.',
    audioUnavailable: 'The project audio is not ready. Try loading it again.',
    editorRate: 'Editor playback: 1.0x',
    play: 'Play at 1.0x',
    pause: 'Pause',
    currentAndTotal: (current: string, total: string) => `${current} / ${total}`,
    segmentLabel: (number: number) => `Segment ${number}`,
    start: 'Start',
    end: 'End',
    setEndpointAccessibilityLabel: (number: number, endpoint: 'start' | 'end') =>
      `Set Segment ${number} ${endpoint}`,
    clearAccessibilityLabel: (number: number) => `Clear Segment ${number}`,
    endpointConfirmation: (endpoint: 'Start' | 'End', time: string) => `${endpoint} set to ${time}`,
    partialError: 'Set both start and end, or clear this segment.',
    nonIntegerError: 'Segment times must use whole milliseconds.',
    outOfBoundsError: 'Segment times must stay within the audio duration.',
    orderError: 'Start must be earlier than end.',
    discardTitle: 'Discard changes?',
    discardMessage: 'Your unsaved segment changes will be lost.',
    discardAction: 'Discard Changes',
    invalidDiscardTitle: 'Incomplete changes cannot be saved',
    invalidDiscardMessage:
      'At least one segment is incomplete or invalid. Discard the entire draft or continue editing.',
    discardAndExit: 'Discard and Exit',
    continueEditing: 'Continue Editing',
    saveErrorTitle: 'Segments could not be saved',
    saveErrorMessage:
      'TempoLoop could not save these segment times. Your existing segments are unchanged.',
    playbackErrorTitle: 'Editor playback failed',
    playbackErrorMessage: 'TempoLoop could not complete that editor playback action.',
    projectNotFoundTitle: 'Project not found',
    projectNotFoundMessage: 'TempoLoop could not find this project in the local library.',
  },
  diagnostics: {
    title: 'Development Diagnostics',
    back: 'Back',
    refresh: 'Refresh',
    clear: 'Clear Diagnostics',
    loading: 'Collecting diagnostics...',
    loadError: 'Diagnostics could not be collected.',
    entryAccessibilityHint: 'Long press to open development diagnostics.',
    nativeSection: 'Native Audio',
    nativeAvailable: 'Module available',
    nativeApiVersion: 'API version',
    lastNativeError: 'Last native error',
    playbackSection: 'Playback',
    playbackState: 'Player state',
    loadedFile: 'Loaded file',
    selectedProject: 'Selected project',
    selectedSegment: 'Selected segment',
    selectedRate: 'Selected rate',
    currentTime: 'Current time',
    duration: 'Duration',
    actualRate: 'Actual rate',
    activeRange: 'Active range',
    storageSection: 'Storage',
    availableDisk: 'Available disk',
    repositorySection: 'Repository',
    projectSchema: 'Project schema',
    waveformSchema: 'Waveform schema',
    repositoryInitialized: 'Initialized',
    projectCount: 'Project count',
    repositoryLastError: 'Last repository error',
    recoveryCodes: 'Recovery diagnostics',
    importSection: 'Import',
    importActive: 'Import active',
    lastImportError: 'Last import error',
    logSection: 'Bounded Local Log',
    logEmpty: 'No development log entries.',
    yes: 'Yes',
    no: 'No',
    none: 'None',
    unavailable: 'Unavailable',
    segmentValue: (number: number) => `Segment ${number}`,
    rateValue: (rate: number) => `${rate}x`,
    schemaValue: (version: number) => `v${version}`,
    activeRangeValue: (start: string, end: string) => `${start} to ${end}`,
    timeValue: (formatted: string, milliseconds: number) => `${formatted} (${milliseconds} ms)`,
    logHeading: (timestamp: string, level: string, event: string) =>
      `${timestamp} [${level}] ${event}`,
  },
} as const;
